apiVersion: v1
kind: Service
metadata:
  name: two-towers-qdrant
  namespace: two-towers
spec:
  selector:
    app: two-towers-qdrant
  ports:
    - name: http
      port: 6333
      targetPort: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: two-towers-qdrant
  namespace: two-towers
spec:
  serviceName: two-towers-qdrant
  replicas: 1
  selector:
    matchLabels:
      app: two-towers-qdrant
  template:
    metadata:
      labels:
        app: two-towers-qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.11.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6333
              name: http
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
  volumeClaimTemplates:
    - metadata:
        name: qdrant-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
